const contentOrder = {
  en: {
    title: "Get a quote",
    name: "Your name or company name",
    location: "Your location (city and country)",
    email: "Your Email",
    phone: "Your phone number",
    product: {
      label: "Product",
      choose: "Choose your product",
      flour: "Wheat flour",
      bran: "Wheat bran",
      semolina: "Semolina",
      oil: "Sunflower oil",
    },
    volume: "Volume (ton)",
    customLabel: {
      question: "Do you need a custom label?",
      no: "We don't need custom label",
      yes: "We need custom label",
    },
    no: "No",
    yes: "Yes",
    comment: "Commentary (your demands to quality level, package etc.)",
    submitBtn: "Send",
    backBtn: "Back",
    required: "* required fields",
  },
  de: {
    title: "Preis anfragen",
    name: "Ihr Name oder Firmenname",
    location: "Ihr Ort (Land, Stadt)",
    email: "Ihr Email",
    phone: "Ihre Handy nummer",
    product: {
      label: "Produkt",
      choose: "Choose your product",
      flour: "Weizenmehl",
      bran: "Weizenkleie",
      semolina: "Grieß",
      oil: "Sonnenblumenöl",
    },
    volume: "Volumen (Tonnen)",
    customLabel: {
      question: "Brauchen Sie Eigenmarkenetikett?",
      no: "Wir btauchen keine Eigenmarke",
      yes: "Wir brauchen Eigenmarke",
    },
    no: "Nein",
    yes: "Ja",
    comment: "Kommentar (Ihre Anforderungen an Qualität, Verpackung etc.)",
    submitBtn: "Schicken",
    backBtn: "Zurück",
    required: "* Pflichtfelder",
  },
  it: {},
  pl: {},
  ua: {
    title: "Запросити цiну",
    name: "Ваше ім'я або назва компанії",
    location: "Ваше місцезнаходження (країна, місто)",
    email: "Ваш Email",
    phone: "Ваш номер телефону",
    product: {
      label: "Продукт",
      choose: "Оберіть продукт",
      flour: "Пшеничне борошно",
      bran: "Пшеничні висівки",
      semolina: "Манна крупа",
      oil: "Соняшникова олія",
    },
    volume: "Об'єм (тонн)",
    customLabel: {
      question: "Вам потрібна своя етикетка на продукті?",
      no: "Нам не потрібна своя етикетка",
      yes: "Нам потрібна своя етикетка",
    },
    no: "Ні",
    yes: "Так",
    comment: "Коментар (Ваші вимоги до рівня якості, упаковки тощо)",
    submitBtn: "Надіслати",
    backBtn: "Назад",
    required: "* обов'язкові поля",
  },
  ru: {
    title: "Узнать цену",
    name: "Ваше имя или название компании",
    location: "Ваше местоположение (страна, город)",
    email: "Ваш Email",
    phone: "Ваш номер телефона",
    product: {
      label: "Продукт",
      choose: "Выберите продукт",
      flour: "Пшеничная мука",
      bran: "Пшеничные отруби",
      semolina: "Манная крупа",
      oil: "Подсолнечное масло",
    },
    volume: "Объём (тонн)",
    customLabel: {
      question: "Вам нужна своя этикетка на продукте?",
      no: "Нам не нужна своя этикетка",
      yes: "Нам нужна своя этикетка",
    },
    no: "Нет",
    yes: "Да",
    comment: "Коментарий (Ваши требования к уровню качества, упаковке и т.д.)",
    submitBtn: "Отправить",
    backBtn: "Назад",
    required: "* обязательные поля",
  },
};

export default contentOrder;
