let content = {
  //Navbar
  company: {
    en: "Dan Agro Trade",
    de: "Dan Agro Trade",
    it: "Dan Agro Trade",
    pl: "Dan Agro Trade",
    ua: "Дан Агро Трейд",
    ru: "Дан Агро Трейд",
  },
  descriptor: {
    en: "a wholesale supplier of food products in Europe",
    de: "Großhandelslieferant für Lebensmittelprodukte in Europa",
    it: "",
    pl: "",
    ua: "",
    ru: "оптовый поставщик пищевых продуктов в Европе",
  },
  ctaPrimary: {
    en: "Get a quote",
    de: "Preis anfragen",
    it: "",
    pl: "",
    ua: "",
    ru: "Узнать цену",
  },
  //Hero
  heroTitle: {
    en: "Export of wheat flour in Europe with delivery",
    de: "Export von Weizenmehl in Europa mit Lieferung",
    it: "",
    pl: "",
    ua: "",
    ru: "Экспорт пшеничной муки по Европе с доставкой",
  },
  heroSubtitle: {
    en: "All sorts and high quality standards directly from a Ukrainian manufacturer",
    de: "Alle Sorten und hohe Qualitätsstandards direkt vom ukrainischen Hersteller",
    it: "",
    pl: "",
    ua: "",
    ru: "Все виды и высокие стандарты качества напрямую от украинского производителя",
  },
  ctaSecondary: {
    en: "Learn more",
    de: "Mehr erfahren",
    it: "",
    pl: "",
    ua: "",
    ru: "Подробнее",
  },
  shippingFeature: {
    en: "Safe delivery from Slovakia to any location in Europe",
    de: "Sichere Lieferung aus der Slowakei an jeden Ort in Europa",
    it: "",
    pl: "",
    ua: "",
    ru: "Надёжная доставка из словакии в любую точку Европы",
  },
  packagingFeature: {
    en: "A custom package with your label",
    de: "Individuelle Verpackung mit Ihrem Etikett",
    it: "",
    pl: "",
    ua: "",
    ru: "Индивидуальная упаковка с Вашей этикеткой",
  },
  orderFeature: {
    en: "Minimal order: 20 tons",
    de: "Minimale Bestellung: 20 Tonnen",
    it: "",
    pl: "",
    ua: "",
    ru: "Минимальный заказ: 20 тонн",
  },

  // Products
  productsTitle: {
    en: { 1: "Our", 2: "production" },
    de: { 1: "Unsere", 2: "Produkte" },
    it: "",
    pl: "",
    ua: "",
    ru: { 1: "Наши", 2: "продукты" },
  },
  flourLabel: {
    en: "Wheat flour",
    de: "Weizenmehl",
    it: "",
    pl: "",
    ua: "",
    ru: "Пшеничная мука",
  },
  branLabel: {
    en: "Wheat bran",
    de: "Weizenkleie",
    it: "",
    pl: "",
    ua: "",
    ru: "Пшеничные отруби",
  },
  semolinaLabel: {
    en: "Semolina",
    de: "Semolina",
    it: "",
    pl: "",
    ua: "",
    ru: "Манная крупа",
  },
  //Advantages
  advantagesTitle: {
    en: { 1: "Our", 2: "advantages" },
    de: { 1: "Unsere", 2: "Vorteile" },
    it: "",
    pl: "",
    ua: "",
    ru: { 1: "Наши", 2: "преимущества" },
  },

  //Company
  companyTitle: {
    en: { 1: "Our", 2: "company" },
    de: { 1: "Unsere", 2: "Firma" },
    it: "",
    pl: "",
    ua: "",
    ru: { 1: "Наша", 2: "компания" },
  },

  //Footer
  contactTitle: {
    en: "Contacts",
    de: "Kontakte",
    it: "",
    pl: "",
    ua: "",
    ru: "Контакты",
  },
  address: {
    en: "Office 402, Solomyanska sqare, 2, 03035 Kiev, Ukraine",
    de: "Office 402, Solomyanska sqare, 2, 03035 Kiew, die Ukraine",
    it: "",
    pl: "",
    ua: "",
    ru: "Офис 402, Соломянская площадь, 2, 03035 Киев, Украина",
  },
  phoneNumber: {
    en: "+49 176 432 342 83",
    de: "+49 176 432 342 83",
    it: "",
    pl: "",
    ua: "",
    ru: "+49 176 432 342 83",
  },
  contactEmail: {
    en: "rkramarev@gmail.com",
    de: "rkramarev@gmail.com",
    it: "",
    pl: "",
    ua: "",
    ru: "rkramarev@gmail.com",
  },
  contactFacebook: {
    en: "Facebook",
    de: "Facebook",
    it: "",
    pl: "",
    ua: "",
    ru: "Facebook",
  },
  newsletter: {
    en: "Newsletter",
    de: "Newsletter",
    it: "",
    pl: "",
    ua: "",
    ru: "Newsletter",
  },
  newsletterEmail: {
    en: "Your Email",
    de: "Ihre Email",
    it: "",
    pl: "",
    ua: "",
    ru: "Ваш Email",
  },
  newsletterButton: {
    en: "Subscribe",
    de: "Folgen",
    it: "",
    pl: "",
    ua: "",
    ru: "Подписаться",
  },
};

export default content;
